- piggy/README.md
애써 무시하고 저멀리 던저놓았던 정규표현식을 제발 졸업하기 위해서 [블로그](https://seob-p.tistory.com/21)에 글을 썻습니다.
소요시간: 약4시간
글쓴소감: 많은 인터넷 예제를 이용, 조기 졸업시도,  현재 유급 중
> [22.06.14] 정규표현식

- gucci/0614.md
글쓰기는 어렵네요.. 하지만 MVVM 이 더어려운듯?
40분
[블로그](https://damagucci-juice.tistory.com/84)
> [화] MVVM 요약본

- eddy/리팩토링_후기.md
- 소요시간: 40분.
- 글쓴 소감: 말로만 리팩토링을 설명하는 게 쉽지가 않다. 코드 예시와 다이어그램을 첨부했다. 근데 내 코드가 구리면 어떡하지? 라는 걱정이 든다.
> [22.06.14] 리팩토링 후기 챕터 1-2

- piggy/README.md
소요시간: 약 1시간
작성 소감: Git은 매일 새로워 ~ 다시 안 당하려면 기록을 해두자..
[해결과정 Wiki](https://github.com/SangHwi-Back/issue-tracker/wiki/Nothing-Compare-Issue-%ED%95%B4%EA%B2%B0)
> Git PR Error 해결

- eddy/리팩토링_후기.md
- 소요시간: 20분
- pigbag이 질문해준 클로저 부분을 보충했다. 일단은 문장이 하나도 안 다듬어져있는데, 그냥 줄줄 쓴 다음 한번 더 다듬을 생각이다. 생일이지만 평소와 하나도 다르지 않은 루틴으로 하루를 보내고 PR로 생일을 마감하고 있는 나... 셀프 칭찬한다.
> [22.06.15] 리팩토링 챕터 2 시작 & Struct를 캡처하는 클로저 보충

- gucci/0615.md
생각을 글로 정리하면서 내가 무엇을 모르는지 생각해보니 좋네요.
15분
> [수] network request 재사용성

- Alex/0616.md
소요시간: 20분
글 소감: 틀리더라도 나의 생각과 의견을 전달해보는 과감함(?)을 가져보는 것도 의미 있는 듯하다.
> [22.6.16] 회고

- piggy/README.md
- 소요시간: 약 2시간 
- 소감: 다른사람의 코드를 보고 이해 할수 있는 능력이 왜 중요한지 알게되었다. 또한, 내가 이해한것을 글로 옮기는 것은 더 힘들다는 것도 알게되었다.. 내가 쓴글이지만.. 내가 아닌 다른사람이 본다면, 이해하기 힘든 글인 것 같다.
> [220616]  다른사람의 설계 이해하기

- eddy/리팩토링_후기.md
- 너무 자세하게 나열하나? 코드의 구체적인 세부 사항을 어느 정도 생략하고 말을 해야할지가 고민이다. 리팩토링을 하는 맛은 코드를 봐야 알 수 있기도 하지만, 너무 장황한 것 같기도 하다.
- 오늘은 글을 너무 쓰기 싫었는데, 막상 시작하니까 그래도 어떻게 꾸역꾸역 쓰게 된다.
- 소요 시간: 30분
> [22.06.16] Delegate, DataSource 합쳐서 하위 Controller로 만들기

- Ocean/20220616회고.md
- 소요시간: 1시간
- 소감: 내가 무엇을 했는지, 무엇이 막히는지를 제대로 파악하는 일은 항상 어렵네요;)
> [22.06.16] 회고

- gucci/0616.md
네트워크 프로그래밍에 이렇게나 약할줄이야..
오랜만에 느끼는 무력감이네요..
하지만 더 성장해야지 ~~
블로그에 글썼어요 블로그로  와주시면 감사요 ~~
[주소](https://damagucci-juice.tistory.com/85)
> [목] Accept header 와 content-type header 의 차이점

- Ocean/20220617회고.md
- Ocean/20220619회고.md
소요 시간: 30분
소감: 오늘은 이번주에 공부한 내용을 돌아보는 것만으로 시간의 대부분이 지나갔다. 살짝 아쉽다🥲
> [22.06.17] 오늘의 회고

- Alex/0617.md
소요시간: 15분
글 소감: 회고가 아닌 계획표를 쓴 느낌...?
> [22.6.17] 회고

- eddy/리팩토링_후기.md
- 소요시간 35분.
- 점점 쓰기가 지겨워진다. 빨리 이 글은 마무리를 지어야겠다.
> [22.06.20] 리팩토링 챕터 3 시작

- Alex/0622.md
소요 시간: 20분
글 소감: 여러 스타일(?)로 글 써보는 것도 재미있네요 :) 오늘은 PR 스타일~
> [22.6.22] 회고

- Ocean/20220622회고.md
소요 시간: 40분
소감: 리팩토링에 대한 글은 설명하기 모호한 부분이 많아서 그런지, 글로 써내기만 하면 많은 것들을 돌아보게 되네요:)
> [22.06.22] 오늘의 회고

- piggy/README.md
- 소요시간: 30분
- 소감:  뭐든 `잘`하는 것은 어렵다.
> [220623] piggy AutoLayout 다시보기

- piggy/README.md
- 소요시간: 약 1시간
- 소감: 잘 이해가 안되서 글을 써보려했으나.. 정리가 안됩니다 하하;;
> [22.06.27] piggy DIContainer의 Flow

- dale/22.6.27.md
- 소요시간: 30분
- 소감: 저는 왜 컬렉션뷰에 집착할까요.. 이유를 모르겠습니다.🙃
> [22.06.27] 오늘의 회고

- piggy/README.md
- 소요시간: 약 40분
- 소감: 혼자 끙끙대지말고 하다가 안되면 물어보자! (에디짱)
> [220628] DIContainer 메모리 문제 해결해보기.

- Ocean/20220629회고.md
소요시간: 약 30분
소감: 글쓰면서 오늘 한 일을 돌아보니, 한 가지 문제에 꽂힐 때가 잦아지는 듯하네요!  너무 치우치지 않도록 조심해야겠습니다😅
> [220629] 회고

- eddy/refactoring_posting.md
- 소요시간 40분.
- 마지막에 후다닥. 후... 이 글 하나 쓰는데 진짜 오래걸렸다. 그래도 6월 내에 끝내서 다행!
- 링크 👉 https://velog.io/@eddy_song/massive-view-controller-refactoring
> [22.06.30] 리팩토링 포스팅 완료!

- dale/UICollectionView.md
- 소요시간: 4시간
- 소감: 생각만하다가 직접 만져보니 상당히 재미집니다. (이미지가 많아 PR에도 올려놓겠습니다)
> A layout object that lets you combine items in highly adaptive and flexible visual arrangements.
>
> 높은 적응력과 시각적으로 유연하게 결합이 가능한 레이아웃 객체
UICompositionalLayout 이란 무엇일까. 예제 코드를 보고 따라서 쳐보기는 했지만, 제대로 살펴본적은 없어 여러가지를 시도해보며 온몸으로 느껴보려고 한다.
**ViewController**
```swift
final class ViewController: UIViewController {
private lazy var dataSource: UICollectionViewDataSource = NormalDataSource()
private lazy var collectionView: UICollectionView = {
let collectionView = UICollectionView(frame: .zero, collectionViewLayout: LayoutFactory.create())
collectionView.register(MyCell.self, forCellWithReuseIdentifier: MyCell.identifier)
collectionView.dataSource = self.dataSource
collectionView.backgroundColor = .blue
return collectionView
}() …
```
> [22.07.04] UICollectionView 톺아보기 시작

- piggy/README.md
-  소요시간: 약 30분
- 소감: Rx가 너무 생소해서 이론을 먼저 배우고있긴한데, 재미가 없긴하네요 ㅋㅋ
> RxSwift(trait)

- piggy/README.md
- 소요시간: 약 1시간
- 소감: DP라 쓰고 Deep PPACK, 이라 읽고싶네요. 넘나 어려운것..
> [220707] piggy_ DP

- gucci/0708.md
2시간 30분(공부시간 별도)
영어 공부를 한건지 iOS 공부를 한건지 모르겠네요..
면접 잘 보게 해주세요 ~~
공식문서 꾸준히 보면 영어 독해 시간 점차 줄게 해주세요 ~~
> 22.07.08: iOS 핵심 멤바

- piggy/README.md
- 소요시간: 30분
- 소감: 분명 내가 쓴글인데..
설명이 조금 부족한거 같으면 원본글 참조해주시면 감사하겠습니다~
https://seob-p.tistory.com/4?category=1031633
> [220711] piggy 내가쓴글 다시보기

- dale/22.7.11.md
- 소요시간: 1시간
- 소감: 큰일났습니다!!! 마음이 급해졌습니다!
> [22.7.11] 회고

- Ocean/20220711회고.md
작성 시간: 40분
소감: 오늘은 성과가 빈약한 것 같네요😅 다들 고생 많으셨습니다.
> [220711] 오늘의 회고

- Ocean/20220713회고.md
소요 시간: 40분
소감: 프로젝트를 정리하다 보니, 시간이 늦었네요😅 오늘도 고생 많으셨습니다!
> [220713] 오늘의 회고

- piggy/README.md
- 소요시간: 30분
- 소감: 복습. 복습을 하자.
저도 아직 잘모르기때문에! 틀린부분 태클 환영입니다!
> [220714] piggy - ios 뷰가 그려지는 과정

- Ocean/20220714회고.md
소요 시간: 1시간
소감: 중요한 내용일수록, 검색한 내용을 정리하고 갈무리하는 데에 시간이 많이 걸리는 듯하네요✍🏻
> [220714] 복습 - lazy 키워드

- Ocean/20220718회고.md
소요 시간: 30분
소감: 이것저것 많이 찾아보고 했는데, 막상 정리해보니 한 게 별로 없네요🤔 그래도 보람찬 하루였습니다:)
> [220718] 오늘의 회고

- Ocean/20220719회고.md
작성 시간: 1시간
소감: 입력 처리는 어떤 플랫폼이든 쉽지 않네요😭 다들 고생 많으셨습니다!
> [220719] 오늘의 회고

- gucci/0720.md
작성 시간 25분
소감 
최단거리 구하기에 한층 가까워진 느낌입니다.
그 순서는 알겠다만 어떻게 거리 계산을 로직에 포함 할지는 미지수네요.
[블로그](https://damagucci-juice.tistory.com/97)
> 2022.07.20: BFS, DFS

- piggy/README.md
- 소요시간: 30분
- 소감: 계속 까먹으니 정리해보자.
> [220720] diffable-piggy

- Ocean/20220721회고.md
작성 시간: 1시간
소감: 내일은 못 푼 문제만 마무리하면, 하루종일 프로젝트할 수 있겠네요:) 투게더분들 고생 많으셨습니다!
> [220721] PS만 하루종일

- piggy/README.md
- 소요시간: 약 30분
- 소감: 조금씩이라도 천천히 써봐야겠다.
얘는 대체 뭘까?
The object you use to manage data and provide cells for a collection view. - 애플
TableView 혹은 CollectionView의 데이터를 관리하고 cell을 제공하기 위한 object.
근데 이미 우리는 dataSource를 사용하고 있지 않나?
이 친구는 어째서 나오게 된걸까?
애플의 표현에 따르면 단하나의 Truth Data를 가질 수 있게 하기 위해서라고 한다.
우리가 일반적인 DataSource를 이용해서 CollectionView를 구현할 때를 살펴보자.
DataSource에 있는 함수들을 이용해서 우리는 View를 그리게 된다.
이 함수들은 어떠한 Model 값에 의존해서 view를 그리게 된다.
여기서 중요한 점은 UI가 가지고 있는 값과 Model이 가지고 있는 값이 차이가 날수 있다는 것이다. 이때 우리가 가끔 봤던 에러가 발생하게 된다.
centralize된 truth가 없다.
그래서 보통 이런 에러는 `reloadData`라는 메서드를 이용해서 Controller가 가지고 있는 값(보통 DataSoure를 Controller에서 구현하므로)과 UI가 가지고 있는 값을 맞춰준다. 
이 방법이 나쁜 것은 아니라고 애플도 인정했지만, 이보다 더 나은 방법을 제시하기 위해 나온 것이 DiffableDataSource이다.
가장 기본적인 DiffableDataSoure를 만들어보자.
**1. SectionIdentifierType과 …
> [220721] diffable-2 piggy

- eddy/sys_programming_2
- 소요시간: 1시간 30분
- 파일 건드리는 거 하나가 뭐가 이렇게 복잡하냐... swift가 그립다
> [22.08.02] 저수준 파일 입출력
